### ISSUE TITLE
URL Cannot be access

### ISSUE THREAD

**Issue by kristfrizh** [vierofernando/bmkg#1]
Hii
thank you for wonderfull works you have done here
I need to check the data i get from this API to your url but i cannot access those url
Is it still valid URL or maybe there is some way the url can be changed for us to access it too
thanks 
berst regards

**Comment by vierofernando** [comment]
sorry, can you try sending a snippet of code for it or explaining the issue in more detail so i can understand?

**Comment by vierofernando** [comment]
closing this since this became a stale issue.
